name: Test Secret Access

on:
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
    steps:
      - name: Echo Secret
        run: echo "Supabase URL is set: $VITE_SUPABASE_URL"
