name: Test Secret Access

on:
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest
    env:
      VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
    steps:
      - name: Echo Secret
        run: echo "Supabase Anon Key is $VITE_SUPABASE_ANON_KEY" 