name: Test Secret Access

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  test-secret:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      VITE_MAPBOX_TOKEN: ${{ secrets.VITE_MAPBOX_TOKEN }}
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
    steps:
      - name: Echo Environment
        run: echo "Testing ${{ inputs.environment }} environment"
        
      - name: Echo Secrets
        run: |
          echo "Environment variables are set:"
          echo "Mapbox Token is set: ${VITE_MAPBOX_TOKEN:0:10}..."
          echo "Supabase URL is set: ${VITE_SUPABASE_URL:0:20}..."
          echo "Supabase Anon Key is set: ${VITE_SUPABASE_ANON_KEY:0:10}..."